sudo: required

os:
  - linux

cache:
  directories:
    - $HOME/docker

services:
  - docker

branches:
  only:
    - master
    - /^(dev)|(dev_.*)$/

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version
  - sudo chmod +x ./scripts/travis_docker_load.sh
  - sudo ./scripts/travis_docker_load.sh

script:
  - sudo chmod +x ./integration_test.sh
  - sudo ./integration_test.sh
  - sudo chmod +x ./scripts/travis_docker_save.sh
  - sudo ./scripts/travis_docker_save.sh
