version: "3"
services:

  db-server:
    image: db-server
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "./data/db:/var/lib/mysql"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  cache-server:
    image: cache-server
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - "./data/cache:/data"
    networks:
      - webnet

  proxy-server:
    image: proxy-server
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - webnet

  service-server:
    image: service-server
    command: mvn -Djava.security.egd=file:/dev/./urandom clean tomcat7:run
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - "cache-server"
      - "db-server"
    volumes:
      - "./service-server.properties:/service-server/src/main/webapp/config.properties"
    networks:
      - webnet

networks:
  webnet:
